url_root: https://subl.ee

author: Heungsub Lee
email:  heungsub@subl.ee
copyright_year_since: 2012

google_analytics: UA-1078484-1

theme: sublue
events:
  4/1:  90s     # April Fools' Day
  4/16: ribbon  # Sinking of MV Sewol
