name: subl.ee

on:
  push:
    branches:
    - master

jobs:
  gh-pages:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Python
      uses: actions/setup-python@v1

    - name: Install
      run: |
        sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev
        pip install -r requirements.txt
        pip install -r lint-requirements.txt

    - name: Lint
      run: |
        flake8 sublee.py
        mypy sublee.py

    - name: Freeze
      run: |
        rm -rf .gh-pages && mkdir .gh-pages
        python sublee.py freeze .gh-pages
        echo subl.ee > .gh-pages/CNAME
        echo "$GITHUB_SHA" > .gh-pages/version.txt

    - name: GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .gh-pages
