name: subl.ee

on:
  push:
    branches:
    - main

jobs:
  link-check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1

  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install requirements
      run: |
        pip install -r requirements.txt # required for mypy
        pip install -r lint-requirements.txt

    - name: Lint
      run: |
        flake8 sublee.py
        mypy sublee.py

  build:
    needs: [link-check, lint]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install requirements
      run: |
        sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev
        pip install -r requirements.txt

    - name: Freeze
      run: |
        python sublee.py freeze _site
        echo "$GITHUB_SHA" > _site/version.txt

    - uses: actions/upload-pages-artifact@v2


  github-pages:
    needs: [build]

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-22.04
    steps:
    - id: deployment
      uses: actions/deploy-pages@v2
